apiVersion: v1
kind: Service
metadata:
  name: spiron
  labels: { app: spiron }
spec:
  clusterIP: None
  selector: { app: spiron }
  ports:
    - name: rpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
